#!/bin/bash
# Build Script, version 1
#
#  Copies contents of dist/ directories in ../ directories determined
#+ to contain projects, and pastes them to
#+ ./src/projects/[project-name]/dist/. Then creates a projects.js
#+ file that declares a global projects variable, which is an array
#+ of strings representing relative paths from ./src to
#+ projects/[project-name].

#  Manually defined paths to project distribution files.
MANUALLY_DEFINED=( "../fend-feed-reader" )

# Remove the projects directory if it exists.
if [ -d "./src/projects" ]
then
  rm -r ./src/projects
fi

#  Get the src/ subdirectories of ../ project directories (excluding
#+ this one).
src_directories=$(find ../ -maxdepth 2 -type d | grep .*/src$ | grep -v projects-index)

echo
echo "Project source directories found:"
echo "$src_directories"
echo
echo "Manually defined project files:"
echo "$MANUALLY_DEFINED"
echo

# For each src/ directory...
for directory in $src_directories
do
  # Extract the project's root directory.
  proj_root=${directory#\.\.\/}
  proj_root=${proj_root%\/*}
  # Check if the project contains a dist/ directory.
  if [ -d "../$proj_root/dist" ]
  # If it has the expected dist/ directory...
  then
    echo "Adding project files to ./src/projects/$proj_root/dist"
    # Make the destination directory.
    mkdir -p ./src/projects/$proj_root/dist
    # Copy the files.
    cp -r ../$proj_root/dist/* ./src/projects/$proj_root/dist/
  # If it doesn't, output a warning to stderr.
  else
    >&2 echo "Warning: ../$proj_root/dist is missing. Did you forget to build it?"
  fi
done

# Add the manually defined distribution files.
for directory in $MANUALLY_DEFINED
do
  # Extract the project's root directory.
  proj_root=${directory#\.\.\/}
  proj_root=${proj_root%%\/*}
  echo "Adding manually defined project files to ./src/projects/$proj_root/dist"
  mkdir -p ./src/projects/$proj_root/dist
  # Copy the files.
  cp -r $directory/* ./src/projects/$proj_root/dist/
done

# Create new contents of projects.js file.
js="var projects = ["
for directory in $(find ./src/projects/ -maxdepth 1 -mindepth 1 -type d | grep -o projects/.*)
do
  # Trim the preceding "projects/".
  directory=${directory:9}
  js="$js'$directory',"
done
# Trim the last "," and close the array.
js=${js%,}
js="$js];"

# Create new projects.js file.
if ! [ -d "./src/scripts" ]
then
  mkdir ./src/scripts
fi
echo "// Generated automatically by \`build-script\`." > ./src/scripts/projects.js
echo $js >> ./src/scripts/projects.js

echo
echo "Created ./src/scripts/projects.js"
echo

exit
